const emigrantServiceData = [
  // Serbia
  {
    id: "1-Work Permits",
    title: "Serbia",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/serbia small.svg",
    jodConditions:
      "To complete assigned tasks, the candidate must be capable in verbal communication and possess a basic understanding of English.",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "850-1100 Euro",
    workingHour: "8-12 hours",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    visaType: "Work Permit 1/2 years renewable",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // {
  //   id: "1-Tourist & Visit",
  //   title: "Serbia",
  //   category: "Tourist & Visit",
  //   image: "/assets/images/game/one.png",
  //   jobcCategory: [
  //     "Block Mason",
  //     "Tiles Mason",
  //     "General Worker",
  //     "Welder",
  //     "Plumber",
  //     "Cleaner",
  //     "Agriculture",
  //     "Driver",
  //   ],
  //   basicSalary: "650-850 Euro",
  //   ageLimit: "18-48 Years Old",
  //   accommodations: "Accommodations by Company and Food by self",
  //   processingTime: "Processing Time: 5-6 months",
  // },
  // {
  //   id: "1-Student",
  //   title: "Serbia",
  //   category: "Student",
  //   image: "/assets/images/game/one.png",
  //   tags: ["jackpot"],
  //   url: "game-details.html",
  // },
  // {
  //   id: "1-Business",
  //   title: "Serbia",
  //   category: "Business",
  //   image: "/assets/images/game/one.png",
  //   jobcCategory: [
  //     "Block Mason",
  //     "Tiles Mason",
  //     "General Worker",
  //     "Welder",
  //     "Plumber",
  //     "Cleaner",
  //     "Agriculture",
  //     "Driver",
  //   ],
  //   basicSalary: "650-850 Euro",
  //   ageLimit: "18-48 Years Old",
  //   accommodations: "Accommodations by Company and Food by self",
  //   processingTime: "Processing Time: 5-6 months",
  // },

  // Spain
  {
    id: "2-Work Permits",
    title: "Spain",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/spain small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },

  // Lithuania
  {
    id: "3-Work Permits",
    title: "Lithuania",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/lithuania small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "3-Tourist & Visit",
    title: "Lithuania",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/lithuania small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "3-Student",
    title: "Lithuania",
    category: "Student",
    image: "/assets/images/emigrant-service/lithuania small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
  },
  {
    id: "3-Business",
    title: "Lithuania",
    category: "Business",
    image: "/assets/images/emigrant-service/lithuania small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },

  // Italy
  {
    id: "4-Work Permits",
    title: "Italy",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/italy small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "4-Tourist & Visit",
    title: "Italy",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/italy small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "4-Student",
    title: "Italy",
    category: "Student",
    image: "/assets/images/emigrant-service/italy small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "4-Business",
    title: "Italy",
    category: "Business",
    image: "/assets/images/emigrant-service/italy small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },

  // Denmark
  {
    id: "5-Work Permits",
    title: "Denmark",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/denmark small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "5-Tourist & Visit",
    title: "Denmark",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/denmark small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "5-Student",
    title: "Denmark",
    category: "Student",
    image: "/assets/images/emigrant-service/denmark small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  {
    id: "5-Business",
    title: "Denmark",
    category: "Business",
    image: "/assets/images/emigrant-service/denmark small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // Poland
  {
    id: "6-Work Permits",
    title: "Poland",
    category: "Work Permits",
    image: "/assets/images/emigrant-service/poland small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // Portugal
  {
    id: "7-Tourist & Visit",
    title: "Portugal",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/portugal  small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // Cyprus
  {
    id: "8-Tourist & Visit",
    title: "Cyprus",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/cyprus Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // France
  {
    id: "9-Tourist & Visit",
    title: "France",
    category: "Tourist & Visit",
    image: "/assets/images/emigrant-service/france Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // Belgium
  {
    id: "10-Business",
    title: "Belgium",
    category: "Business",
    image: "/assets/images/emigrant-service/Belgium Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // Belgium
  {
    id: "11-Luxembourg",
    title: "Luxembourg",
    category: "Business",
    image: "/assets/images/emigrant-service/Luxembourg Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // USA
  {
    id: "12-USA",
    title: "USA",
    category: "Student",
    image: "/assets/images/emigrant-service/USA Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
  // EU
  {
    id: "12-EU",
    title: "EU",
    category: "Student",
    image: "/assets/images/emigrant-service/EU Small.svg",
    jobcCategory: [
      "Block Mason",
      "Tiles Mason",
      "General Worker",
      "Welder",
      "Plumber",
      "Cleaner",
      "Agriculture",
      "Driver",
    ],
    basicSalary: "650-850 Euro",
    ageLimit: "18-48 Years Old",
    accommodations: "Accommodations by Company and Food by self",
    processingTime: "Processing Time: 5-6 months",
    requiredDocuments: [
      "Scanned copy of passport",
      "Updated CV with relevant experience",
      "Recent photo EU Standards (3.5 x 4.5 cm, face covering 80%)",
      "Completed questionnaire (Form will be provided)",
      "Medical & Police clearance  ",
    ],
  },
];

export default emigrantServiceData;
